# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://www.alexerling.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Alex Erling # Your name will go here
  description: "Alex Erling's personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Software Engineer</h1>
     <p>HTML, CSS, JavaScript, Ruby on Rails and more.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: alex.erling@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook: alex.erling
  flickr:
  github: AlexErling
  google_plus:
  instagram: alexerling
  linkedin:  https://www.linkedin.com/in/alexander-erling-aa0b9682/
  pinterest:
  reddit:
  soundcloud: soundcloud.com/beatsbyerl
  stack_exchange:  https://stackexchange.com/users/11333222/alex-erling
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-105092923-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

plugins: [jekyll-paginate]
